name : "publish npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-versions: 16
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{secrets.VUE_FORM_ELEMENT}}
